camel.route-template[unshippedqty-in].template-id=eda-proto-consumer
camel.route-template[unshippedqty-in].kafka.source_topics={{unshippedqty.topic}}
camel.route-template[unshippedqty-in].kafka.secret={{kafka.secret}}
camel.route-template[unshippedqty-in].kafka.target_route=unshippedqty-business
camel.beans.oebsDs.url={{oebs.db.url}}
camel.beans.oebsDs.password={{oebs.db.password}}
